structure(list(url = "https://httpbin.org/status/400", status_code = 400L, 
    headers = structure(list(date = "Tue, 03 Jan 2023 23:12:43 GMT", 
        `content-type` = "text/html; charset=utf-8", `content-length` = "0", 
        connection = "keep-alive", server = "gunicorn/19.9.0", 
        `access-control-allow-origin` = "*", `access-control-allow-credentials` = "true"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 03 Jan 2023 23:12:43 GMT", 
            `content-type` = "text/html; charset=utf-8", `content-length` = "0", 
            connection = "keep-alive", server = "gunicorn/19.9.0", 
            `access-control-allow-origin` = "*", `access-control-allow-credentials` = "true"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw(""), date = structure(1672787563, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000145, 
    connect = 0.000147, pretransfer = 0.000322, starttransfer = 0.254059, 
    total = 0.254148)), class = "response")
